src/libos/crates/async-rt/src/config.rs
src/libos/crates/async-rt/src/executor.rs
src/libos/src/entry/enclave.rs

#26 [async-rt] Should remove set_sched_callback? 
- remove sched_callback in async-rt config and executor.
- add background task (io_uring poll function) when init async-rt.
- need shutdown these tasks before shutdown executor (not implemented yet).
- consider add attribute / status to `task` struct later.
- use yield() in background task to avoid running too long. 
- (one insight: without yield, io_uring poll function will always running.)
needs to do:
- distinguish background tasks and user tasks.    (add attributes for `task` struct ?)
- select suitable thread for background tasks.
- add status for task 
- avoid waking up repeatedly. 
- do not wake up tasks with shutdown-status. 
- shutdown background tasks in executor.shutdown().

[async-rt] Remove sched_callback.

---

src/libos/Cargo.lock
src/libos/crates/io-uring-callback/Cargo.toml
src/libos/crates/io-uring-callback/examples/sgx/enclave/src/lib.rs
src/libos/crates/io-uring-callback/examples/tcp_echo.rs
src/libos/crates/io-uring-callback/src/io_handle.rs
src/libos/crates/io-uring-callback/src/lib.rs

- To implement cancel, we pass a IoUring reference parameter for cancel().   (It's complicated to store IoUring ref in the IoToken, which causes circular-reference, lifetime problem ...)
- Add do_timeout for libos using io-uring timeout.
- Only use do_timeout() in do_sigtimedwait() for now. Since io-uring timeout cannot support signal wake-up and remaining time (nanosleep)
- require:  wake up by signal
- require:  calculate remaining time if waked up by signal.

Add cancel and timeout for io-uring-callback.

---

src/libos/crates/async-rt/src/executor.rs
src/libos/crates/async-rt/src/parks/mod.rs

Fix a system hung issue.
When unpark is invoked before the park, the thread would hung. (There is another bug in Rust SGX SDK, the timeout does not work.)

[async-rt]Fix system hung issue (park unpark)

---

src/libos/Cargo.lock
src/libos/Cargo.toml
src/libos/src/fs/procfs/meminfo.rs
src/libos/src/lib.rs
src/libos/src/misc/sysinfo.rs
src/libos/src/prelude.rs
src/libos/src/process/do_exit.rs
src/libos/src/process/do_spawn/mod.rs
src/libos/src/vm/chunk.rs
src/libos/src/vm/free_space_manager.rs
src/libos/src/vm/mod.rs
src/libos/src/vm/process_vm.rs
src/libos/src/vm/user_space_vm.rs
src/libos/src/vm/vm_area.rs
src/libos/src/vm/vm_chunk_manager.rs
src/libos/src/vm/vm_layout.rs
src/libos/src/vm/vm_manager.rs
src/libos/src/vm/vm_perms.rs
src/libos/src/vm/vm_range.rs
src/libos/src/vm/vm_util.rs
test/mmap/main.c

Improve userspace VM management 

---

.github/workflows/demo_test.yml
src/pal/src/pal_interrupt_thread.c
test/exit_group/main.c
test/pthread/main.c

The NGO interrupt implementation depends on SIG64 signal. There is an unknown bug which make the demos randomly failed.
So temporary disable this feature to enable other development tasks.

Temporary disable interrupt thread

---

src/libos/src/entry/context_switch/arch_prctl_x86-64.S
src/libos/src/entry/context_switch/switch.h
src/libos/src/entry/context_switch/switch_x86-64.S

Enable simulation mode on the system which does not support rdfsbase/wrfsbase

Support simulation mode when the rdfsbase/wrfsbase instructions are not

---

demos/cluster_serving/install-dependencies.sh
demos/flink/download_flink.sh

The OpenJDK 11 has a broken symlink, the copy_bom tool is not able to work with this symlink, so remove it.

Remove a broken symlink in openjdk 11, fix flink and cluster_serving demo

---

src/libos/src/util/mem_util.rs

This commit fixed an Occlum security issue. The researchers from KU
Leuven (Belgium) and the University of Birmingham (UK) found it and
reported it to Occlum team. Thank you, Jo Van Bulck, Frank Piessens,
Fritz Alder, David Oswald, Jesse Spielman and Sam Thomas.

Check the buffer address before copy the data from the buffer

---

src/libos/src/entry/enclave.rs
src/libos/src/entry/syscall.rs
src/libos/src/ipc/mod.rs
src/libos/src/ipc/shm.rs
src/libos/src/ipc/syscalls.rs
src/libos/src/lib.rs
src/libos/src/process/do_exit.rs
src/libos/src/process/do_getuid.rs
src/libos/src/process/mod.rs
src/libos/src/process/syscalls.rs
src/libos/src/vm/mod.rs
src/libos/src/vm/user_space_vm.rs
test/Makefile
test/shm/Makefile
test/shm/main.c

1. Add support for System V shared memory;
2. Add some tests for it.
More details are shown in the [issue page](https://github.com/occlum/occlum/issues/863)
**Other changes**: 
1. Add new file `src/libos/src/process/do_getuid.rs`, and move the implementaion of `do_getgid()`, `do_getegid()`, `do_getuid()` and `do_geteuid()` to `src/libos/src/process/do_getuid.rs`, since the `Shm::newshm()` in `src/libos/src/ipc/shm.rs` needs to invoke `no async` `do_euid()` and `do_egid()`;
2. Remove duplicate check `USER_SPACE_VM_MANAGER.verified_clean_when_exit()` in `src/libos/entry/main.rs` ([details](https://github.com/occlum/ngo/compare/beb1d1c410a8831938544021eb83129e21c533d0..0b061993c1585b8bae394259d941f2814b2bfa2a)), such check has been performed in `src/libos/src/vm/user_space_vm.rs: …

[libos] Add support for shm

---

.github/workflows/demo_test.yml
demos/filebench/dl_and_build_filebench.sh
demos/filebench/filebench.patch
demos/filebench/filebench.yaml
demos/filebench/run_benchmark.sh
demos/filebench/workloads/fileserver.f
demos/filebench/workloads/oltp.f
demos/filebench/workloads/readfiles.f
demos/filebench/workloads/varmail.f
demos/filebench/workloads/videoserver.f

Filebench tool can generate **real-world workloads** to test **file system** and **block device**
1. Add demo with four workloads ([Sworndisk paper evaluation](https://github.com/occlum/lets-go-sworn-disk/issues/48#666))
2. Add Filebench_test to ci:demo_test workflow

[demo] Add Filebench demo

---

src/libos/crates/Cargo.toml
src/libos/crates/async-file/examples/common/bench.rs
src/libos/crates/async-io/src/event/event_counter.rs
src/libos/crates/async-io/src/event/mod.rs
src/libos/crates/async-io/src/lib.rs
src/libos/crates/async-io/src/util/channel.rs
src/libos/crates/async-rt/src/bench/mod.rs
src/libos/crates/async-rt/src/executor.rs
src/libos/crates/async-rt/src/lib.rs
src/libos/crates/async-rt/src/time/instant.rs
src/libos/crates/async-socket/examples/common/tcp_echo.rs
src/libos/crates/block-device/src/block_device_ext.rs
src/libos/crates/host-socket/tests/echo.rs
src/libos/crates/io-uring-callback/examples/sgx/enclave/src/lib.rs
src/libos/crates/io-uring-callback/examples/tcp_echo.rs
src/libos/crates/io-uring-callback/src/lib.rs
src/libos/crates/sgx-disk/Cargo.toml
src/libos/crates/sgx-disk/benches/disk_bench.rs
src/libos/crates/sgx-disk/src/host_disk/io_uring_disk.rs
src/libos/src/entry/enclave.rs
src/libos/src/fs/builtin_disk.rs
src/libos/src/fs/file_ops/close.rs
src/libos/src/fs/syscalls.rs
src/libos/src/io_uring.rs

This PR is intended to identify and fix performance issues regarding the async runtime, async I/O, io_uring, and block devices.
As the first steps, this PR adds a series of benchmarks. Here are some of the results.
* Benchmark results of `async_rt` primitives
* Benchmark results of `Channel<u8>` in `async_io`
* Benchmark results of several types of disks in `sgx-disk`
Based on the observations acquired from the benchmarks, this PR fixes several performance issues in async_rt and io_uring_callack.
* [[async-rt] Fix the premature sleep of the executor](https://github.com/tatetian/ngo/commit/6e28598693cd9d84f493d41492cde3a00323634b)
* [[io-uring-callback] Improve the efficiency of completion polling](https://github.com/tatetian/ngo/commit/7297664b245ed7c7965e1f74777d1c6b92a40a67)
* …

Identify and fix performance issues in async code

---

src/libos/crates/sgx-disk/src/host_disk/sync_io_disk.rs

`SyncIoDisk` scalability  issue: #262 
Improvement:
- Use `libc::ocall::preadv64` and `pwritev64` API for host file reads/writes
- Remove the mutex on file

[sgx-disk] Improve SyncIoDisk scalability

---

.github/workflows/composite_action/prebuild/action.yml
.gitmodules
src/libos/crates/Cargo.toml
src/libos/crates/block-device/src/lib.rs
src/libos/crates/block-device/src/util/block_range.rs
src/libos/crates/block-device/src/util/mod.rs
src/libos/crates/page-cache/Cargo.toml
src/libos/crates/page-cache/src/cached_disk.rs
src/libos/crates/page-cache/src/lib.rs
src/libos/crates/page-cache/src/page.rs
src/libos/crates/page-cache/src/page_alloc.rs
src/libos/crates/page-cache/src/page_cache.rs
src/libos/crates/page-cache/src/page_evictor.rs
src/libos/crates/page-cache/src/page_handle.rs
src/libos/crates/page-cache/src/page_state.rs
src/libos/crates/page-cache/src/prelude.rs
src/libos/crates/page-cache/tests/cached_disk_tests.rs
src/libos/crates/page-cache/tests/page_cache_tests.rs

Add page-cache crate https://github.com/occlum/ngo/issues/267.

[crates] Add page-cache crate

---

src/libos/crates/vdso-time/src/lib.rs
src/libos/crates/vdso-time/src/sys.rs

Github CI ubuntu 20.04 VM starts to use Linux 5.15 kernel. Without this patch, the crate test will panic.
After checking the Linux source code, the `vdso_data` struct hasn't changed since 5.9. Thus can safely extend the support to 5.18.

[vdso] Extend vdso support to Linux 5.18

---

.github/workflows/demo_test.yml

The previous error is due to the early kill of the container.
Heavily tested here: https://github.com/jessehui/ngo/actions/runs/2629545066

[CI] Fix pytorch demo test

---

demos/linux-ltp/syscalls-occlum

It will introduce too much overhead if we check the memory protection perm
for every user space address, so we dismiss the test case.

Fix the SEGV in LTP test

---

.github/workflows/benchmarks.yml
demos/benchmarks/fio/configs/fio-microbench.fio
demos/benchmarks/fio/download_and_build_fio.sh
demos/benchmarks/fio/fio_microbench.sh
demos/benchmarks/fio/result_template.json
demos/benchmarks/fio/run_fio_on_occlum.sh

This PR add FIO test to benchmark ci.
The workflow `FIO_Test` runs a microbenchmark on schedule.
Testing here:
- GitHub action: [here](https://github.com/lucassong-mh/ngo/actions/runs/3366568401/jobs/5583194405)
- Charts on GitHub Pages: [here](https://lucassong-mh.github.io/ngo/dev/benchmarks/)

[benchmark ci] Add fio to benchmark ci

---

src/libos/crates/async-rt/src/executor.rs
src/libos/crates/async-rt/src/scheduler/entity.rs
src/libos/crates/async-rt/src/scheduler/local_scheduler/mod.rs
src/libos/crates/async-rt/src/scheduler/local_scheduler/runqueues.rs
src/libos/crates/async-rt/src/scheduler/mod.rs
src/libos/crates/async-rt/src/scheduler/timeslice.rs
src/libos/crates/async-rt/src/scheduler/vcpu_selector.rs
src/libos/crates/async-rt/src/scheduler/yield_.rs

This commit unpark vcpus when large amounts of tasks are coming, which makes cpu utilization more efficient.
Besides, this commit have better scheduling performance.
**NGO sysbench with this commit:**
**NGO sysbench without this commit:**

[async-rt] Support unparking vcpus when enqueueing tasks

---

etc/template/Occlum.yaml
src/libos/Cargo.toml
src/libos/crates/page-cache/src/page_alloc.rs
src/libos/crates/page-cache/tests/cached_disk_tests.rs
src/libos/crates/page-cache/tests/page_cache_tests.rs
src/libos/src/config.rs
src/libos/src/fs/rootfs.rs
test/Occlum.yaml
tools/gen_internal_conf/src/main.rs

Now user can configure `page_cache_size` in Occlum.yaml under `mount.options`

Make page cache size configurable in Occlum.yaml

---

tools/installer/deb/toolchains/golang/rules
tools/installer/rpm/toolchains/golang/occlum-toolchains-golang.spec
tools/toolchains/golang/build.sh

In default, occlum-go uses musl-gcc. Users can configure occlum-go to use gcc like below.
" CC=gcc occlum-go build "

Make occlum-go support gcc/glibc option

---

src/exec/src/bin/occlum_exec_client.rs
src/libos/Cargo.lock
src/libos/crates/errno/Cargo.toml
src/libos/crates/errno/src/errno.rs
src/libos/crates/errno/src/lib.rs
tools/occlum

1. [Print the raw errno if it is not an expected value](https://github.com/occlum/ngo/commit/8e2765a92f66b7a0b6a8c678e1c20dbadf1c0c3f)
2. [Improve the usability of occlum start/exec/stop cmd](https://github.com/occlum/ngo/commit/32cc2d027277afcd95acacf1ca5db141eced979c)

Pick some commits
