occlum/ngo

- src/libos/crates/async-io/src/file/flags.rs
- src/libos/crates/host-socket/src/prelude.rs
- src/libos/crates/host-socket/src/stream/mod.rs
- src/libos/crates/host-socket/src/stream/states/common.rs
- src/libos/crates/host-socket/src/stream/states/connected/recv.rs
- src/libos/crates/host-socket/src/stream/states/connected/send.rs
- src/libos/crates/host-socket/src/stream/states/init.rs
- src/libos/crates/host-socket/src/stream/states/listen.rs
- src/libos/crates/io-uring-callback/src/io_handle.rs
- src/libos/src/net/socket_file.rs
- src/libos/src/net/syscalls.rs
- Fix a bug of io-uring-callback: `iohandle.await` can not be waken up
- Support nonblocking mode
- Support status flags (o_nonblock)
> Support nonblocking mode

- src/libos/src/fs/dev_fs/dev_shm.rs
- src/libos/src/fs/dev_fs/mod.rs
- src/libos/src/fs/rootfs.rs
- test/device/main.c
- test/symlink/main.c
> Mount ramfs at '/dev/shm'

- src/libos/src/config.rs
- src/libos/src/lib.rs
- tools/occlum_build.mk
- tools/protect-integrity/App/App.cpp
- tools/protect-integrity/Enclave.edl
- tools/protect-integrity/Enclave/Enclave.cpp
Deps on: https://github.com/occlum/ngo/pull/72
> Modify the protect-integrity tool to print result on file

- src/libos/src/entry/syscall.rs
- test/time/main.c
- tools/occlum
Deps on:https://github.com/occlum/ngo/pull/72
> Add time syscall and default localtime support

- src/libos/crates/async-io/src/file/flags.rs
- src/libos/src/fs/hostfs.rs
- src/libos/src/fs/inode_file.rs
- src/libos/src/fs/sefs/sgx_storage.rs
- test/fs_perms/main.c
- test/hostfs/main.c
- test/include/test.h
- test/include/test_fs.h
- test/mmap/main.c
- test/truncate/main.c
Deps on https://github.com/occlum/ngo/pull/72
> Add O_TRUNC support in open syscall and Rewrite the truncate test

- src/libos/crates/async-rt/src/lib.rs
- src/libos/crates/host-socket/src/lib.rs
> [crates] Add log capabilites to libos crates

- docs/code_coverage.md
- docs/dragonwell_install.md
- docs/encrypted_image.md
- src/libos/crates/async-io/src/file/file.rs
- src/libos/crates/async-io/src/fs/stat_buf.rs
- src/libos/src/fs/file_handle.rs
- src/libos/src/fs/file_ops/stat.rs
- src/libos/src/fs/pipe.rs
- test/pipe/main.c
> Add fstat support for pipe

- src/libos/Cargo.lock
- src/libos/crates/async-rt/Cargo.toml
- src/libos/crates/async-rt/src/executor.rs
- src/libos/crates/async-rt/src/lib.rs
- src/libos/crates/async-rt/src/task/mod.rs
- src/libos/crates/async-rt/src/task/task.rs
- src/libos/crates/async-rt/src/task/tirqs.rs
- src/libos/crates/async-rt/src/wait/macros.rs
- src/libos/crates/async-rt/src/wait/waiter.rs
- src/libos/src/entry/thread.rs
- src/libos/src/process/do_clone.rs
- src/libos/src/process/do_exit.rs
- src/libos/src/process/do_spawn/mod.rs
- src/libos/src/process/process/mod.rs
- src/libos/src/process/thread/builder.rs
- src/libos/src/process/thread/mod.rs
- src/libos/src/sched/sched_agent.rs
- src/libos/src/signal/do_kill.rs
- src/libos/src/signal/do_sigpending.rs
- src/libos/src/signal/do_sigprocmask.rs
- src/libos/src/signal/do_sigreturn.rs
- src/libos/src/signal/do_sigtimedwait.rs
- src/libos/src/signal/sig_num.rs
- src/libos/src/signal/sig_queues.rs
- src/libos/src/signal/sig_set.rs
- test/exit_group/main.c
The PR consists of three main commits (among other minor commits):
* [async-rt] Add Task Interrupt ReQuests
* [libos] Force thread exit with interrupts
* [libos] Force signal delivery with interrupts
> Support interrupts

- src/libos/src/entry/enclave.rs
- src/libos/src/entry/syscall.rs
- src/libos/src/process/do_exit.rs
- src/libos/src/process/do_getpid.rs
- src/libos/src/process/do_spawn/mod.rs
- src/libos/src/process/do_wait4.rs
- src/libos/src/process/mod.rs
- src/libos/src/process/pgrp.rs
- src/libos/src/process/process/builder.rs
- src/libos/src/process/process/idle.rs
- src/libos/src/process/process/mod.rs
- src/libos/src/process/spawn_attribute.rs
- src/libos/src/process/syscalls.rs
- src/libos/src/process/table.rs
- src/libos/src/signal/do_kill.rs
- test/Makefile
- test/Occlum.json
- test/getpid/main.c
- test/pgrp/Makefile
- test/pgrp/main.c
> Add process group implementation and support set/getpgid, set/getpgrp

- src/libos/src/vm/process_vm.rs
Signed-off-by: Zheng, Qi <huaiqing.zq@antgroup.com>
> Return current break if brk failed

- src/libos/src/fs/file_table.rs
- src/libos/src/poll/do_epoll/epoll_file.rs
- src/libos/src/process/thread/mod.rs
- test/server_epoll/main.c
> [libos] Fix epoll file's handling with closed files

- src/libos/crates/async-io/src/util/channel.rs
> [libos] Fix the pipe blocking read issue

- .github/workflows/demo_test.yml
- src/libos/src/net/mod.rs
- src/libos/src/net/socket_file.rs
- src/libos/src/net/syscalls.rs
Recover the basic demo and sofaboot demo
> Socket protocol

- src/libos/src/fs/file_ops/ioctl/builtin/termios.rs
- src/libos/src/fs/file_ops/ioctl/mod.rs
> [libos] Fix TCGETS/TCSETS using wrong termios type definition

- src/libos/src/fs/file_ops/dup.rs
- src/libos/src/misc/rlimit.rs
Merge from https://github.com/occlum/occlum/pull/703
> Merge patches from Occlum to fix LTP test failure cases

- src/libos/crates/async-io/src/file/file.rs
- src/libos/crates/async-io/src/util/channel.rs
- src/libos/crates/host-socket/src/datagram/mod.rs
- src/libos/crates/host-socket/src/datagram/sender.rs
- src/libos/crates/host-socket/src/lib.rs
- src/libos/crates/host-socket/src/stream/states/connected/send.rs
- src/libos/src/entry/syscall.rs
- src/libos/src/fs/file_ops/sendfile.rs
- src/libos/src/poll/do_poll.rs
- src/libos/src/process/syscalls.rs
- test/unix_socket/main.c
This PR can fix several bugs that are found by running gvisor test suite.
All the fixed gvisor tests are：
bad_test,  futex_test,  poll_test,  preadv2_test,  pwritev2_test,  readv_test,  rtsignal_test,  select_test,  socket_blocking_ip_test.
> Fix several bugs found by gvisor test suite

- src/libos/src/entry/enclave.rs
- src/pal/src/pal_interrupt_thread.c
It can elimilate most of the interrupt signal sent.
The sofaboot (JDK 8/11) demo, unit test "exit_group, pthread“ can pass with this change.
> Only send interrupt signal when task stuck in userspace over 250ms

- src/libos/src/fs/event_file.rs
- src/libos/src/poll/do_epoll/epoll_entry.rs
- src/libos/src/poll/do_epoll/epoll_file.rs
This can fix gVisor `epoll_test` case.
> [libos] Fix several epoll related bugs

- src/Enclave.edl
- src/libos/Cargo.lock
- src/libos/Makefile
- src/libos/crates/async-rt/Cargo.toml
- src/libos/crates/async-rt/src/executor.rs
- src/libos/crates/async-rt/src/lib.rs
- src/libos/crates/async-rt/src/ocalls/async_rt_ocalls.c
- src/libos/crates/async-rt/src/ocalls/sgx_async_rt_ocalls.edl
- src/libos/crates/async-rt/src/task/mod.rs
- src/libos/crates/async-rt/src/time/mod.rs
- src/libos/crates/async-rt/src/time/wheel.rs
- src/libos/crates/async-rt/src/wait/mod.rs
- src/libos/src/entry/enclave.rs
- src/pal/Makefile
- src/pal/src/pal_api.c
- src/pal/src/pal_timer_thread.c
- src/pal/src/pal_timer_thread.h
- test/server/main.c
- test/signal/main.c
> Reduce the CPU usage of the timer wheel thread

- demos/redis/redis.conf
- src/libos/crates/Cargo.toml
- src/libos/crates/async-io/src/socket/addr/c_sock_addr.rs
- src/libos/crates/async-io/src/socket/addr/ipv6.rs
- src/libos/crates/async-io/src/socket/addr/mod.rs
- src/libos/crates/async-io/src/socket/domain.rs
- src/libos/crates/async-io/src/socket/mod.rs
- src/libos/crates/async-rt/Cargo.toml
- src/libos/crates/async-rt/src/lib.rs
- src/libos/crates/host-socket/Cargo.toml
- src/libos/crates/host-socket/src/common/operation.rs
- src/libos/crates/host-socket/src/ioctl/get_ifreq.rs
- src/libos/crates/host-socket/src/util/untrusted_circular_buf.rs
- src/libos/crates/host-socket/tests/echo.rs
- src/libos/src/fs/file_ops/ioctl/mod.rs
- src/libos/src/net/addr.rs
- src/libos/src/net/mod.rs
- src/libos/src/net/socket_file.rs
- src/libos/src/net/syscalls.rs
> Fix some socket related bugs and add IPv6 support

- .github/workflows/main.yml
- src/libos/Makefile
- src/libos/crates/host-socket/src/prelude.rs
- src/libos/crates/host-socket/src/stream/states/connected/send.rs
- test/client/Makefile
- test/client/main.c
- test/server/Makefile
- test/server/main.c
Fix the bug when the user buffer is bigger than kernel send buffer
> Fix user big send buffer error

- .github/workflows/code_coverage.yaml
- codecov.yml
- src/libos/Makefile
- src/libos/src/fs/hostfs.rs
- src/libos/src/time/mod.rs
Add LTP + basic test cases for code coverage test CI.
With current test cases, the coverage rate is about 76%.
> [ci] Add initial code coverage CI test

- src/libos/src/entry/enclave.rs
- src/libos/src/fs/fs_ops/mount.rs
- src/libos/src/fs/fs_ops/sync.rs
- src/libos/src/fs/fs_view.rs
- src/libos/src/fs/mod.rs
- src/libos/src/fs/rootfs.rs
Filesystem should be the owner of its root inode
> [libos] Change ROOT_INODE to ROOT_FS

- src/libos/src/signal/do_sigreturn.rs
- test/pgrp/main.c
The current signal stack implementation is not align with the glibc, update the size, gap size and validate it.
> Update the signal stack implementation

- .github/workflows/composite_action/hw/action.yml
- .github/workflows/composite_action/sim/action.yml
- .github/workflows/demo_test.yml
- .github/workflows/hw_mode_test.yml
- .github/workflows/main.yml
- demos/fish/download_and_build.sh
- demos/grpc/grpc_tls/Makefile.patch
- demos/grpc/grpc_tls/README.md
- demos/grpc/grpc_tls/download_and_install_grpc.sh
- demos/grpc/grpc_tls/download_and_install_openssl.sh
- demos/grpc/grpc_tls/gen-cert.sh
- demos/grpc/grpc_tls/greeter_secure_client.cc
- demos/grpc/grpc_tls/greeter_secure_server.cc
- demos/grpc/grpc_tls/grpc_secure_client.yaml
- demos/grpc/grpc_tls/grpc_secure_server.yaml
- demos/grpc/grpc_tls/prepare_occlum_instance.sh
- demos/python/flask/README.md
- demos/python/flask/build_occlum_instance.sh
- demos/python/flask/flask.yaml
- demos/python/flask/gen-cert.sh
- demos/python/flask/install_python_with_conda.sh
- demos/python/flask/rest_api.py
- demos/python/flask/run_flask_on_occlum.sh
1. Upgrade CI environment to Ubuntu 20.04;
2. Add grpc_tls_test and flask_tls_test to Demo Test;
3. Remove CentOS test
> [ci] Upgrade CI environment to ubuntu20.04

- demos/linux-ltp/syscalls-occlum
Disable LTP statx03 testcase for now to make code coverage test pass
> [demos] Disable LTP statx03 testcase

- .github/workflows/demo_test.yml
- demos/rocksdb/dl_and_build_rocksdb.sh
- demos/rocksdb/rocksdb.yaml
- demos/rocksdb/run_benchmark.sh
Workflow:
1. Build Rocksdb from src
2. Build a simple example and db_bench tool
3. Run example and benchmark(fillseq,fillrandom,readseq,readrandom,deleteseq) in Occlum
4. Run the same benchmark on host for a performance comparsion
> [demo] Add RocksDB demo and benchmark test

- .github/workflows/composite_action/hw/action.yml
The network of new ci machine works fine so we disable proxy and ustc crates-io source.
> [hw_ci] Disable proxy and ustc crates-io source on new machine

- .github/workflows/benchmarks.yml
Disable push triggered benchmark CI test.
> [benchmark ci] Schedule to run everyday at 10PM UTC

- src/libos/src/fs/file_ops/link.rs
- src/libos/src/fs/file_ops/mkdir.rs
- src/libos/src/fs/file_ops/rename.rs
- src/libos/src/fs/file_ops/rmdir.rs
- src/libos/src/fs/file_ops/symlink.rs
- src/libos/src/fs/file_ops/unlink.rs
- src/libos/src/fs/fs_view.rs
- src/libos/src/fs/fspath.rs
- src/libos/src/fs/mod.rs
- src/libos/src/fs/rootfs.rs
- src/libos/src/net/unix/trusted/trusted_addr.rs
- test/hostfs/main.c
- test/mkdir/main.c
- test/open/main.c
- test/rename/main.c
- test/stat/main.c
Remember to merge https://github.com/occlum/sefs/pull/45 first
> Fix the issue when path is suffixed by "/"

- src/libos/src/fs/procfs/pid/maps.rs
- src/libos/src/fs/procfs/pid/mod.rs
- src/libos/src/process/do_spawn/exec_loader.rs
- src/libos/src/process/do_spawn/mod.rs
- src/libos/src/process/elf_file.rs
- src/libos/src/vm/chunk.rs
- src/libos/src/vm/mod.rs
- src/libos/src/vm/process_vm.rs
- src/libos/src/vm/vm_area.rs
- src/libos/src/vm/vm_chunk_manager.rs
- src/libos/src/vm/vm_manager.rs
- src/libos/src/vm/vm_perms.rs
- src/libos/src/vm/vm_util.rs
- test/mmap/main.c
- test/procfs/main.c
`Add support for /proc/self(pid)/` is a bit different from the implementation of Occlum due to FS changes in NGO.
> Apply recent VM related patches from Occlum

- tools/occlum
Merge two commits from Occlum.
f73d41 Make it accordance for occlum package name and extracted dir name
05d4c7 Add similation and debug mode occlum package check and support
> [tools] Make occlum package support simulation mode

- src/libos/crates/block-device/src/block_buf.rs
- src/libos/crates/block-device/src/block_device.rs
- src/libos/crates/block-device/src/block_device_as_file.rs
- src/libos/crates/block-device/src/mem_disk.rs
- src/libos/crates/block-device/src/prelude.rs
- src/libos/crates/sgx-disk/src/crypt_disk.rs
- src/libos/crates/sgx-disk/src/host_disk/io_uring_disk.rs
- src/libos/crates/sgx-disk/src/host_disk/sync_io_disk.rs
- src/libos/crates/sgx-disk/src/pfs_disk/mod.rs
- src/libos/crates/sgx-disk/src/pfs_disk/open_options.rs
This PR includes:
(It cherry-pick some old commits)
Usability:
- Implement `Debug` for disks
Bugfix:
- Fix bugs in `CryptDisk`, `PfsDisk`, `BlockDeviceAsFile`
> Improve sgx-disk and block-device

- test/Makefile
- test/epoll/Makefile
- test/epoll/main.c
This adds failed cases found in https://github.com/occlum/occlum/pull/1011.
> Add test cases for epoll

- src/libos/src/entry/thread.rs
- src/libos/src/process/do_vfork.rs
- src/libos/src/process/mod.rs
- src/libos/src/process/thread/builder.rs
- src/libos/src/process/thread/mod.rs
- src/libos/src/signal/do_sigreturn.rs
- test/vfork/Makefile
- test/vfork/main.c
Porting from https://github.com/occlum/occlum/pull/1022
> Make vfork stop parent child threads

- src/pal/src/pal_error.c
Port from https://github.com/occlum/occlum/pull/1021
> Update pal error message

- src/libos/src/process/do_wait4.rs
- test/client/main.c
- test/server/Makefile
- test/server/main.c
Port from: https://github.com/occlum/occlum/pull/1050
> [libos] Fix exit_group not interrupt wait4

- src/libos/crates/async-io/src/socket/addr/ipv4.rs
- src/libos/crates/async-io/src/socket/addr/ipv6.rs
- src/libos/crates/async-io/src/socket/addr/mod.rs
- src/libos/crates/async-io/src/socket/addr/netlink.rs
- src/libos/crates/async-io/src/socket/addr/unix.rs
- src/libos/crates/errno/src/errno.rs
- src/libos/crates/errno/src/to_errno.rs
- src/libos/crates/host-socket/src/common/mod.rs
- src/libos/crates/host-socket/src/common/operation.rs
- src/libos/crates/host-socket/src/datagram/generic.rs
- src/libos/crates/host-socket/src/datagram/mod.rs
- src/libos/crates/host-socket/src/datagram/netlink.rs
- src/libos/crates/host-socket/src/datagram/receiver.rs
- src/libos/crates/host-socket/src/datagram/sender.rs
- src/libos/crates/host-socket/src/stream/mod.rs
- src/libos/crates/sgx-untrusted-alloc/src/box_.rs
- src/libos/src/net/socket_file.rs
- src/libos/src/net/syscalls.rs
- src/libos/src/net/unix/mod.rs
- src/libos/src/net/unix/trusted/stream/stream.rs
- src/libos/src/net/unix/trusted/trusted_addr.rs
- src/libos/src/util/mem_util.rs
Rebase new commits and replace #301.
> Fix udp socket
